services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    networks:
      - app_network
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: erick
      POSTGRES_PASSWORD: 1234
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
